### PR TITLE
[Fix] `packages/react` issue with `useQuery` not supporting dynamic query parameters

### PR DESCRIPTION
**Pull request by Chriztiaan**
Original issue reported at https://github.com/powersync-ja/powersync-js/issues/323.
Dynamic query dependencies would warn with the following if the query parameter array changed in size:
 `Warning: The final argument passed to useMemo changed size between renders. The order and size of this array must remain constant. Previous: [] Incoming: [xxxxxxxxxxxxx]
`

Tested with the following to verify that it works now:
```
const [params, setParams] = React.useState<string[]>([]);
const { data } = useQuery(`select * from lists where id=?`, params);

onclick:: setParams(["some-uuid"])
```

The change from `React.useMemo(() => {}, [...array]);` to `React.useMemo(() => {},[JSON.stringify(array)])` should not introduce any issues, as valid query parameters are expected to be serialisable.

### CODE REVIEW

**Review by DominicGBauer — APPROVED** [review]

**Comment by DominicGBauer** [comment]
We may want to look at something like this in the future https://github.com/sandiiarov/use-deep-compare#readme.

**Comment by guillempuche** [comment]
Very cool Christian!

**Comment by fooware** [comment]
I just got hit with this today in our process of porting over our codebase from Electric. Spent quite some time trying to figure out which `useMemo` it was, until I found this. Thanks for fixing it @Chriztiaan!

Any idea when this could be merged and released? Is there any canary / nightly one could test after it is merged?

**Review by stevensJourney — APPROVED** [review]

**Comment by Chriztiaan** [comment]
@fooware, I'll release this soonest and ping you.

**Pull request merged**
