### PR TITLE
chore: rename packages

### PR DESCRIPTION
**Pull request by DominicGBauer**
## Description
Rename packages to use @powersync npm prefix

@journeyapps/powersync-sdk-react-native ->  @powersync/react-native
@journeyapps/powersync-sdk-web -> @powersync/web
@journeyapps/powersync-sdk-common -> @powersync/common
@journeyapps/powersync-react -> @powersync/react
@journeyapps/powersync-attachments -> @powersync/attachments

packages/powersync-sdk-react-native -> packages/react-native
packages/powersync-sdk-web -> packages/web
packages/powersync-sdk-common -> packages/common
packages/powersync-react -> packages/react
packages/powersync-attachments -> packages/attachments

## Work Done
* Renamed packages 
* Changed imports and references

## Other things
- [ ] Merge this: https://github.com/powersync-ja/docs-powersync-gitbook/pull/2

### CODE REVIEW

**Comment by Chriztiaan** [comment]
Would it make sense to hold off on merging this until after the watched query issue users have reported is confirmed to be fixed?

**Comment by DominicGBauer** [comment]
> Would it make sense to hold off on merging this until after the watched query issue users have reported is confirmed to be fixed?

Why would that have an effect on this?

**Comment by Chriztiaan** [comment]
> > Would it make sense to hold off on merging this until after the watched query issue users have reported is confirmed to be fixed?
> 
> Why would that have an effect on this?

Might be a bit of a chore for users to switch packages as we are still trying to get a version in front of them that resolves the issue. Minor?

**Comment by DominicGBauer** [comment]
I did the change in the vue package and changesets adapted to the new package name and version. What is preventing us from merging the current changesets?

**Comment by benitav** [comment]
Will deprecating the current packages (and adding a deprecation message) happen in a subsequent PR?

**Comment by DominicGBauer** [comment]
@benitav Ralf will need to add a deprecation message on npmjs.org

**Review by rkistner — APPROVED** [review]

**Pull request merged**
